"""Добавили модель картинок для поста

Revision ID: 8c873c8a1158
Revises: 158a2401f279
Create Date: 2025-08-17 11:09:20.781131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c873c8a1158'
down_revision: Union[str, Sequence[str], None] = '158a2401f279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('users', 'Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'name')
    op.drop_table('images')
    # ### end Alembic commands ###
