"""Добавили модель картинок для поста

Revision ID: f02d9a69d59d
Revises: c43c7b9cb3f9
Create Date: 2025-08-17 11:09:36.015672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02d9a69d59d'
down_revision: Union[str, Sequence[str], None] = 'c43c7b9cb3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('users', 'Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
